### ISSUE TITLE
Admin Login Creditenals

### ISSUE THREAD

**Issue by foxy4096** [zihadul-haque/django-mosh#1]

**Comment by foxy4096** [comment]
are you alive man?

**Comment by zihadul-haque** [comment]
yeah!
any question?

**Comment by foxy4096** [comment]
I can't believe you replied!!!!!!

**Comment by zihadul-haque** [comment]
🙂🙂🙂

**Comment by foxy4096** [comment]
I still don't belive I opened a issue for getting the admin login cred for django admin, instead I could have just deleted the sqlite db and remigrate it.
